### ISSUE TITLE
Support Monorepos & Multiple Package Managers

### ISSUE THREAD

**Issue by dbanty** [dobby-dev/dobby#98]
The general idea is to have the scope of a conventional commit correlate to a specific package. Here's my current thinking:

- [ ] #148
- [ ] #149
- [ ] #151
- [ ] #26
- [ ] #152
- [ ] #153
- [ ] #154

## Sample Non-Monorepo Config

This is what the `dobby.toml` for this repo might include after the change. This would preserve the existing behavior today, but be more explicit.

```toml
[[packages]]
versioned_files = ["Cargo.toml"]
changelog = "CHANGELOG.md"
version_prefix = "v."
```

## Sample Monorepo Config

Here's an example config for a monorepo which contains both Rust and Python code which should be versioned separately (depending on the change) and released separately.

```toml
[[packages]]
versioned_files = ["python/pyproject.toml"]
changelog = "python/CHANGELOG.md"
scopes = ["python"]
version_prefix = "python@"

[[packages]]
versioned_files = ["rust/Cargo.toml"]
changelog = "rust/CHANGELOG.md"
scopes = ["rust"]
version_prefix = "rust@"
```

With that config, here are some commits and their effects:

1. `feat: A new global feature`: Bumps both `python/pyproject.toml` and `rust/Cargo.toml` with the "minor" semver rule. Adds an identical entry to both changelogs.
2. `fix(something): a fix`: Bumps both `python/pyproject.toml` and `rust/Cargo.toml` with the "patch" semver rule. Adds an identical entry to both changelogs. Scope is effectively ignored because it isn't registered.
3. `feat(rust): Did something to Rust`: only modifies `rust/Cargo.toml` and `rust/CHANGELOG.md`.
4. `feat(python): Did something to Python`: only modifies `python/pyproject.toml` and `python/CHANGELOG.md`.

So the `rust/CHANGELOG.md` would look something like this:

```md
## 1.2.0 - 2021-02-11

### Features

- A new global feature
- Did something to Rust

### Fixes

- a fix
```

`scopes` should be optional so that if someone wants to version to two projects in lock-step (have every commit count toward both of them) then they can.
